### ISSUE TITLE
Choose a new non-temporary name

### ISSUE THREAD

**Issue by GarboMuffin** [GarboMuffin/p3#4]
Because p3 is meant to be temporary

Restrictions:

 - Cannot use the word "Scratch" in any way except "for Scratch"
 - Try to avoid the word HTMLifier to avoid confusion with https://sheeptester.github.io/htmlifier/

**Comment by YOYITsM3M8** [comment]
turbopackage?

**Comment by sargent-coding** [comment]
> turbopackage?

ooooh nice idea

**Comment by powerbox1000** [comment]
# A good name for p3 might be:
* TurboForkphorus
* TurboWarp + Forkphorus
* Ultimate Scratch Compiler

**Comment by AnnoyedArt1256** [comment]
FTPackager (if you want to you can also choose TFPackager to not be confused with Famitracker)

**Comment by GarboMuffin** [comment]
If I actually continue working on this, the most likely name right now is "TurboWarp Packager" and the URL will become packager.turbowarp.org or something like that.

**Comment by GarboMuffin** [comment]
Closing per above
