### ISSUE TITLE
Run project in TurboWarp or Forkphorus button

### ISSUE THREAD

**Issue by jemunm378** [GarboMuffin/p3#9]
I think there should be a run project in TurboWarp or Forkphorus button. The layout of the three buttons will be: "Package/Run it in TurboWarp/Run it in Forkphorus.

**Comment by GarboMuffin** [comment]
Having a "preview" button that opens the project in the selected runtime & options might be worthwhile.

Having separate buttons for each runtime is unnecessary because the user already selects a runtime

**Comment by jemunm378** [comment]
Yeah maybe that will be better :P
